### ISSUE TITLE
Data Reports questions

### ISSUE THREAD

**Issue by EJDinki** [EJDinki/messe#21]
How to handle Report Index with no ID?

Should we add a link from survey index to view report for that survey?

How to handle short answer questions? Just remove them from the report?

Report format/layout

**Comment by ajm5774** [comment]
i think that short answer questions are already excluded from the data
passed from the controller action i wrote. Why would a report not have an
ID? all surveys should have IDs. Redirecting to 404 is fine i think, You
can use the mockups as a reference for what the views should look like. I
would use the admin layout still.

-Andrew

**Comment by ajm5774** [comment]
oops, im stupid. haha

**Comment by EJDinki** [comment]
Forward to survey index maybe?

Add button for view report

Remove short answer questions
