### ISSUE TITLE
Change Survey Name to Survey Title

### ISSUE THREAD

**Issue by jonshippling** [EJDinki/messe#25]
Instead of the survey being called "Adult", change it to "Welcome to the Adult Survey", in order to give the admins more control over the look and feel of the survey.

**Comment by EJDinki** [comment]
The name of this issue and the description you(Jon) wrote don't seem like the same thing to me. Did we want to make the edit survey page say "Survey Title" instead of "Survey Name"? Because that's what I thought it was before I read the description.
