### ISSUE TITLE
Short answer answers seem to be getting into data of other questions for reports

### ISSUE THREAD

**Issue by EJDinki** [EJDinki/messe#28]
Stuff I put into short answers appear to be getting into the data for reports of other questions. Still need to investigate further, most likely something in ReportController

**Comment by rjv9645** [comment]
Someone did not properly assign the ShortAnswer questions to use the ShortAnswer view we had and instead just used TextAreaFor. Using HtmlElementFor will have unexpected outcomes with our overridden ModelBinder. Please use just TextArea and create the proper name and id based on our agreed upon standards.
