### ISSUE TITLE
Slider questions broken

### ISSUE THREAD

**Issue by rjv9645** [EJDinki/messe#30]
There seems to be a javascript bug in the latest code. I cannot drag the sliders in slider questions

**Comment by jonshippling** [comment]
I'll look into this, as it's most likely stemming from the javascript I put in for timeouts.

**Comment by rjv9645** [comment]
I feel that I must not have pulled all the proper files on my laptop, because with the latest code, it works on my desktop. My fault, sorry for putting this as a bug.
