### ISSUE TITLE
Exhibit questions not being submitted correctly

### ISSUE THREAD

**Issue by EJDinki** [EJDinki/messe#44]
It seems that survey answers aren't getting saved to the DB correctly.

It seems like the first exhibit is always put as an answer. Also an answer of empty string ("") is also submitted.

**Comment by EJDinki** [comment]
After checking again this bug is still in full effect.

Steps to reproduce (you could probably check the database but this is how I've been noticing it)
1. Go through a survey and select whatever exhibits (or don't choose any)
2. Go to report
3. Download report with raw data
4. Check raw data for that exhibit question, you'll see both a empty string and exhibit 1 submitted with your submission, no matter what you picked (or even if you pick no exhibits)

You'll also see it show up in the pie charts in the legend you'll always see "1" and ""

**Comment by rjv9645** [comment]
I have reproduced the steps as mentioned. Since I failed fixing this the first time, can someone else please look into this bug? I'm a little stumped.

**Comment by EJDinki** [comment]
For anyone interested in the cause:

For whatever reason, doing String.Split(';') seems likes it's always giving us an empty string as one of the elements in the array returned (along with the correct values).

In the code we split and then find the ID for each, but we do FirstOrDefault, so when it gets to the empty string the default exhibit (1) is returned.

The next loop takes these ID's, which have been put into another ";" delimited string and does a split(';') on that, and puts each into an answer, again we get an empty string in this loop so exhibit "" is put into an answer.

And that's why exhibit 1 and "" were always showing up in each submission.

I skipped the whole making the exhibit names into ID's step, which makes reports nicer. Also when looping on the string.split(';') I now check that the string is not null or empty before doing anything with it.
