### ISSUE TITLE
(watch)Cannot choose default slider choice without interacting with it

### ISSUE THREAD

**Issue by EJDinki** [EJDinki/messe#55]
I don't remember this being the case before, so I'm assuming it was broken with choice changes.

If you don't touch a slider, nothing gets committed, so if you wanted neutral and don't touch the slider and just hit next, it will pretend you didn't answer the question. You have to move the slider to another value and back to neutral to get it to submit that.

**Comment by rjv9645** [comment]
Actually, I do believe this was the case before. Andrew would know more.

**Comment by ajm5774** [comment]
I set a default value so that they dont have to interact with it to submit something. This isnt really a solution though, so im putting it on watch
