### ISSUE TITLE
Mutes not persisted across submissions

### ISSUE THREAD

**Issue by EJDinki** [EJDinki/messe#56]
Maybe this was intentional, I would suggest saving whether mute is on or not on the session so it's muted for everyone.

Also the option to turn sound on or off by default or disable it all together via survey edit might be nice.

Staff could also mute the tablet, so this is probably low priority stuff

**Comment by rjv9645** [comment]
Do you mean so it isn't muted for everyone? 

I was imagining that the user would mute it if they didn't like the noise. If the museum wanted it muted for everybody they could do as you say and mute the tablet. 

The mute was thrown together quickly and there is most certainly a better way of doing it.
