### ISSUE TITLE
tablet kiosk mode

### ISSUE THREAD

**Issue by jonshippling** [EJDinki/messe#77]
I'm currently working on putting the tablet into full kiosk mode. I found some target flag arguments that'll let us open up a Chrome browser that'll be in a full-screen kiosk mode that only allows the user to stay on a specific domain: ".../chrome.exe --kiosk --host-rules="MAP \* localhost:80" where localhost:80 is the domain you want to keep the user on. The only problem now is finding a way to disable gestures on the tablet so that users don't swipe out of Chrome and access the tablet.

**Comment by jonshippling** [comment]
I'm currently working on putting the tablet into full kiosk mode. I found some target flag arguments that'll let us open up a Chrome browser that'll be in a full-screen kiosk mode that only allows the user to stay on a specific domain: ".../chrome.exe --kiosk --host-rules="MAP * localhost:80" where localhost:80 is the domain you want to keep the user on. The only problem now is finding a way to disable gestures on the tablet so that users don't swipe out of Chrome and access the tablet.

**Comment by jonshippling** [comment]
For the tablet I have, I made Chrome open up the somee website for the survey on startup, created a new Chrome shortcut on the desktop, and put the following for the Target on the properties menu: ".../chrome.exe --kiosk --host-rules="MAP \* http://museumsurvey.somee.com"

**Comment by rjv9645** [comment]
Once the tablet is set to go to kiosk mode on startup, how would the museum staff get around that? Is there a password to get out of the kiosk mode?

**Comment by jonshippling** [comment]
The tablet isn't set to go into kiosk mode right off of startup, the chrome shortcut has to be launched and then it is set to kiosk mode. As for getting around that, the only way I've figured out without a physical keyboard is to restart the tablet.

**Comment by jonshippling** [comment]
Right now my deployment process is as such:
Restart tablet by holding down power button
Start tablet back up
Open the not-kiosk mode Chrome shortcut
Set the new survey URL as the homepage for chrome
Close the browser
Open the kiosk-mode chrome shortcut

**Comment by jonshippling** [comment]
That's the quick dirty hack job I've come up with, and I'm not sure there's a better way. I'll keep researching it.

**Comment by jonshippling** [comment]
So it looks like it's impossible to disable the right-side swipe to open the charms bar on Windows 8, and I haven't found any freeware that'll disable that on a system-wide level. The only feasible solution I have right now is to somehow physically cover up the the right-most 30-50 pixels, which seems to be the threshold for the charms menu swipe-to-open.

**Comment by rjv9645** [comment]
http://www.tomshardware.com/faq/id-2082953/disable-swipe-windows.html

What about that? Go into table settings and disable charm/corner navigation

**Comment by jonshippling** [comment]
I tried that, turning the charm/corner navigation "off" does nothing for the swipe right-to-left charm bar.

**Comment by EJDinki** [comment]
Can confirm. Looked into myself a bit. The original Kisok Mode I thought was available, isn't available for Windows 8.1 Standard edition.

http://superuser.com/questions/697572/cant-see-assigned-access-options-in-windows-8-1

I think this might have been brought up a few weeks ago.

**Comment by EJDinki** [comment]
The best thing I think we can do is make use of Child accounts.

Make sure the admin account has a password

Make a Kiosk Mode account, make it password free (in case someone logs out)

Make it a child account in account settings

In control panel go to User Accounts and Family Saftey. Click on the Kiosk Mode account

You can now white list apps and websites. So we can only allow Chrome and whatever domain the sites listed on (Tom might have to help set that up depending on how the tablets end up connecting to the server)

This doesn't solve all the issues, people can still change some settings and switch out of the app, but it would prevent a kid doing any damage, I think, and block them from the internet(aka porn)

**Comment by EJDinki** [comment]
I tried the approach here:

http://superuser.com/questions/821887/windows-8-real-kiosk-mode

But using chrome.exe instead of internet explorer. Left me with a blue screen and unable to do anything. Perhaps because chrome won't work like that, not sure, but could try monkeying down that approach some more.

Oh also for that approach, it was running all 3 commands, instead of waiting for your to alt-f4 the browser like that guy said. So when I tried it I took out the last line. Just thought I'd mention that.

**Comment by ajm5774** [comment]
If lockheed martin can get cd keys for professional, then maybe we can upgrade the tablets

**Comment by EJDinki** [comment]
I had some more success with my previous approach.

I took what that guy had and swapped out the opening of IE to be Jon's command line command for chrome, plus "....somee.com" at the end so it opens the survey up right away.

The result is a tablet that can't do anything but use that page. The charms don't work, the hardware windows button doesn't work. Everything window related to the browser is gone (no tabs, address bar, back buttons, bookmarks, etc.)

The only downsides are
1. the guy from that link suggests using alt-f4 to kill the program and get back to "regular mode". I can't see a way to do that without an external keyboard. This means you gotta hold the power button and shut it down and reboot to get it usable.
1. While the browser stuff and everything else is disabled, you can still right click (hold press or two finger tap). This allows anything you can access in the right click menu. The most destructive being if you click an image (like discovery center logo on start screen) you can  "search for images like this on google" and it brings up google. I'm not sure why it's not blocked by Jon's command line argument. Maybe we can blacklist google.com

I can show you guys this in person Thursday but I think it fits our needs.
